### ISSUE TITLE
Sortie Skill Inheritance Menu crashes when there are no units in the absent force (undeploys units)

### ISSUE THREAD

**Issue by triabolicals** [Raytwo/Cobalt#43]
### System Firmware Version

Ryujinx

### Atmosphere Version

Ryujinx

### Cobalt Version

1.0

### Can the crash be consistently reproduced?

Yes

### At what moment does the crash happen?

- [ ] Before the Switch boot animation
- [ ] After the Switch boot animation
- [ ] While the picture is displayed on boot
- [ ] While the spinner is displayed on boot
- [X] At random
- [ ] After a long time playing

### Details

Skill inheritance menu crashes if all units are deployed when trying to access it in the sortie.

**Bandaid solution:** Can be avoided by undeploying one unit first then going into the menu.

### Crash report

```shell
00:00:05.170 |I| HLE.OsThread.22 SurfaceFlinger CreateLayerFromId: Creating layer 1
00:00:05.172 |I| HLE.OsThread.22 SurfaceFlinger CreateLayerFromId: Creating layer 2
00:00:05.525 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:00:06.527 |E| HLE.OsThread.10 Gpu WaitOnSyncpoint: Wait on syncpoint 1 for threshold 2 took more than 1000ms, resuming execution...
00:00:10.256 |I| GPU.MainThread Gpu LoadShaders: Shader cache loaded.
00:00:10.371 |E| .NET ThreadPool Worker [mvk-info] Created 3 swapchain images with initial size (1325, 700) and contents scale 1.0 for screen DELL AW2518HF.
00:00:12.362 |I| HLE.OsThread.8 Loader OpenDataStorageByDataId: Opened AddOnContent Data TitleID=0100A6301214F001
00:00:12.363 |I| HLE.OsThread.8 Loader OpenDataStorageByDataId: Opened AddOnContent Data TitleID=0100A6301214F001
00:00:12.451 |W| HLE.GuestThread.21 KernelSvc OutputDebugString: Patching using text MSBT: message/us/usen/skill.txt

00:00:12.504 |W| HLE.GuestThread.21 KernelSvc OutputDebugString: Patching using text MSBT: message/us/usen/levelup.txt

00:00:12.798 |I| HLE.OsThread.7 AudioRenderer AcquireSessionId: Registered new output (0)
00:00:13.731 |W| HLE.GuestThread.21 KernelSvc OutputDebugString: save base Skill

00:00:13.736 |W| HLE.GuestThread.21 KernelSvc OutputDebugString: Diffing and patching Skill took 5ms

00:00:14.077 |W| HLE.GuestThread.21 KernelSvc OutputDebugString: save base AssetTable

00:00:14.093 |W| HLE.GuestThread.21 KernelSvc OutputDebugString: Diffing and patching AssetTable took 17ms

00:00:14.258 |W| HLE.GuestThread.21 KernelSvc OutputDebugString: save base God

00:00:14.260 |W| HLE.GuestThread.21 KernelSvc OutputDebugString: Diffing and patching God took 2ms

00:00:15.712 |W| HLE.GuestThread.21 KernelSvc OutputDebugString: Cache supports

00:00:15.712 |W| HLE.GuestThread.21 KernelSvc OutputDebugString: Before parsing support book

00:00:15.712 |W| HLE.GuestThread.21 KernelSvc OutputDebugString: After parsing support book

00:00:15.744 |W| HLE.GuestThread.21 KernelSvc OutputDebugString: RNG Mode set to None

00:00:15.744 |W| HLE.GuestThread.21 KernelSvc OutputDebugString: Cutscenes/Movies are not skipped

00:00:15.744 |W| HLE.GuestThread.21 KernelSvc OutputDebugString: Arena battles are not skipped

00:00:15.744 |W| HLE.GuestThread.21 KernelSvc OutputDebugString: Chief is set to level 0

00:00:15.744 |W| HLE.GuestThread.21 KernelSvc OutputDebugString: Growth set to save file default

00:00:15.744 |W| HLE.GuestThread.21 KernelSvc OutputDebugString: Protag Skill found on person #0 - MPID_Lueur

00:00:15.745 |W| HLE.GuestThread.21 KernelSvc OutputDebugString: Characters are set to default.

00:00:19.324 |W| HLE.GuestThread.21 KernelSvc OutputDebugString: Patching using text MSBT: message/us/usen/skill.txt

00:00:19.386 |W| HLE.GuestThread.21 KernelSvc OutputDebugString: Patching using text MSBT: message/us/usen/levelup.txt

00:00:19.602 |W| HLE.GuestThread.21 KernelSvc OutputDebugString: Region: us/usen

00:00:21.107 |W| HLE.GuestThread.21 KernelSvc OutputDebugString: Title loop

00:00:22.508 |W| HLE.GuestThread.21 KernelSvc OutputDebugString: Displayed HP: 22, Class Base HP: 22, Enhance HP: 0

00:00:22.508 |W| HLE.GuestThread.21 KernelSvc OutputDebugString: Old Cap 0 to New Cap 0

00:00:23.759 |I| HLE.OsThread.22 ServiceSfdnsres GetAddrInfoRequestImpl: Guest network access disabled, DNS Blocked: api.github.com
00:00:23.759 |W| HLE.GuestThread.21 KernelSvc OutputDebugString: Failed to check for updates: IoError(Kind(NetworkDown))

00:00:26.682 |W| HLE.GuestThread.21 KernelSvc OutputDebugString: RNG Mode set to None

00:00:26.682 |W| HLE.GuestThread.21 KernelSvc OutputDebugString: Cutscenes/Movies are skipped

00:00:26.682 |W| HLE.GuestThread.21 KernelSvc OutputDebugString: Map Tutorials and Dialogue are skipped

00:00:26.683 |W| HLE.GuestThread.21 KernelSvc OutputDebugString: Arena battles are skipped

00:00:26.683 |W| HLE.GuestThread.21 KernelSvc OutputDebugString: Chief is set to level 5

00:00:26.683 |W| HLE.GuestThread.21 KernelSvc OutputDebugString: Growth set to save file default

00:00:26.683 |W| HLE.GuestThread.21 KernelSvc OutputDebugString: Characters are set to default.

00:00:27.262 |W| HLE.GuestThread.21 KernelSvc OutputDebugString: Replacing Lua script: Scripts/Common.txt

00:00:27.275 |W| HLE.GuestThread.21 KernelSvc OutputDebugString: Player Army Average Level: 6

00:00:27.275 |W| HLE.GuestThread.21 KernelSvc OutputDebugString: NPC Level 10

00:01:01.166 |I| HLE.GuestThread.21 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Fire Emblem Engage, PID: 98
   0x000000003f800000


00:01:01.170 |I| HLE.GuestThread.21 Cpu PrintGuestRegisterPrintout: Guest CPU registers:
	X[00]:	0x0000000000000001
	X[01]:	0x0000000000000000
	X[02]:	0x000000166666dea0
	X[03]:	0x0000000000000000
	X[04]:	0x0000000000000001
	X[05]:	0x0000000000000000
	X[06]:	0x000000000000004c
	X[07]:	0x0000000000000000
	X[08]:	0x00000016666cb280
	X[09]:	0x0000000000000010
	X[10]:	0x00000000000001c0
	X[11]:	0x0000000000000000
	X[12]:	0x000000000000001d
	X[13]:	0x00000015c0a07ff0
	X[14]:	0x00000000000059dd
	X[15]:	0x00000000000059dd
	X[16]:	0x000000000e7849f0
	X[17]:	0x000000000f7bdee4 (sdk:0x349ee4)	=> nn::os::detail::InternalCriticalSectionImplByHorizon::Leave()
	X[18]:	0x00000016666fb000
	X[19]:	0x0000001666425a00
	X[20]:	0x0000001665cdc1a0
	X[21]:	0x000000000f46b688
	X[22]:	0x00000049f27081f8 (SP:-0x0038)
	X[23]:	0x000000000f45c748
	X[24]:	0x000000000f45c828
	X[25]:	0x0000000000000000
	X[26]:	0x0000000000000008
	X[27]:	0x0000000000000000
	X[28]:	0x0000000000000000
	FP:	0x00000049f27081d0 (SP:-0x0010)
	LR:	0x000000000f2fea0c
	SP:	0x00000049f27081c0 (SP)
	PC:	0x000000000f2fea84


00:01:01.170 |E| HLE.GuestThread.21 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000000000020.
00:01:01.193 |E| HLE.GuestThread.21 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write, Boolean precise, Nullable`1 exemptId) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Memory/Tracking/MemoryTracking.cs:line 281
   at Ryujinx.Cpu.AppleHv.HvExecutionContext.DataAbort(MemoryTracking tracking, UInt64 vcpu, UInt32 esr) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Cpu/AppleHv/HvExecutionContext.cs:line 227
   at Ryujinx.Cpu.AppleHv.HvExecutionContext.SynchronousException(HvMemoryManager memoryManager, HvVcpu& vcpu) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Cpu/AppleHv/HvExecutionContext.cs:line 189
   at Ryujinx.Cpu.AppleHv.HvExecutionContext.Execute(HvMemoryManager memoryManager, UInt64 address) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Cpu/AppleHv/HvExecutionContext.cs:line 160
   at Ryujinx.Cpu.AppleHv.HvCpuContext.Execute(IExecutionContext context, UInt64 address) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Cpu/AppleHv/HvCpuContext.cs:line 25
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.HLE/HOS/ArmProcessContext.cs:line 60
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.HLE/HOS/Kernel/Threading/KThread.cs:line 1264
   at System.Threading.Thread.StartCallback()
```

**Comment by Raytwo** [comment]
Fix recently
